language: go
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install build-essential pkg-config libosmesa6-dev libglu1-mesa-dev
go:
  - 1.1
  - 1.2
  - 1.3
  - tip
notifications:
  email: false
